//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private int AgeField;
        
        private float SalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetContactsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContacts", ReplyAction="*")]
        UnitTestProject1.ServiceReference1.GetContactsResponse GetContacts(UnitTestProject1.ServiceReference1.GetContactsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContacts", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.GetContactsResponse> GetContactsAsync(UnitTestProject1.ServiceReference1.GetContactsRequest request);
        
        // CODEGEN: Generating message contract since element name GetContactResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContact", ReplyAction="*")]
        UnitTestProject1.ServiceReference1.GetContactResponse GetContact(UnitTestProject1.ServiceReference1.GetContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContact", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.GetContactResponse> GetContactAsync(UnitTestProject1.ServiceReference1.GetContactRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContacts", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReference1.GetContactsRequestBody Body;
        
        public GetContactsRequest() {
        }
        
        public GetContactsRequest(UnitTestProject1.ServiceReference1.GetContactsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetContactsRequestBody {
        
        public GetContactsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactsResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReference1.GetContactsResponseBody Body;
        
        public GetContactsResponse() {
        }
        
        public GetContactsResponse(UnitTestProject1.ServiceReference1.GetContactsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContactsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestProject1.ServiceReference1.Contact[] GetContactsResult;
        
        public GetContactsResponseBody() {
        }
        
        public GetContactsResponseBody(UnitTestProject1.ServiceReference1.Contact[] GetContactsResult) {
            this.GetContactsResult = GetContactsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContact", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReference1.GetContactRequestBody Body;
        
        public GetContactRequest() {
        }
        
        public GetContactRequest(UnitTestProject1.ServiceReference1.GetContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetContactRequestBody() {
        }
        
        public GetContactRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReference1.GetContactResponseBody Body;
        
        public GetContactResponse() {
        }
        
        public GetContactResponse(UnitTestProject1.ServiceReference1.GetContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContactResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestProject1.ServiceReference1.Contact GetContactResult;
        
        public GetContactResponseBody() {
        }
        
        public GetContactResponseBody(UnitTestProject1.ServiceReference1.Contact GetContactResult) {
            this.GetContactResult = GetContactResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : UnitTestProject1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<UnitTestProject1.ServiceReference1.WebService1Soap>, UnitTestProject1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReference1.GetContactsResponse UnitTestProject1.ServiceReference1.WebService1Soap.GetContacts(UnitTestProject1.ServiceReference1.GetContactsRequest request) {
            return base.Channel.GetContacts(request);
        }
        
        public UnitTestProject1.ServiceReference1.Contact[] GetContacts() {
            UnitTestProject1.ServiceReference1.GetContactsRequest inValue = new UnitTestProject1.ServiceReference1.GetContactsRequest();
            inValue.Body = new UnitTestProject1.ServiceReference1.GetContactsRequestBody();
            UnitTestProject1.ServiceReference1.GetContactsResponse retVal = ((UnitTestProject1.ServiceReference1.WebService1Soap)(this)).GetContacts(inValue);
            return retVal.Body.GetContactsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.GetContactsResponse> UnitTestProject1.ServiceReference1.WebService1Soap.GetContactsAsync(UnitTestProject1.ServiceReference1.GetContactsRequest request) {
            return base.Channel.GetContactsAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.GetContactsResponse> GetContactsAsync() {
            UnitTestProject1.ServiceReference1.GetContactsRequest inValue = new UnitTestProject1.ServiceReference1.GetContactsRequest();
            inValue.Body = new UnitTestProject1.ServiceReference1.GetContactsRequestBody();
            return ((UnitTestProject1.ServiceReference1.WebService1Soap)(this)).GetContactsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReference1.GetContactResponse UnitTestProject1.ServiceReference1.WebService1Soap.GetContact(UnitTestProject1.ServiceReference1.GetContactRequest request) {
            return base.Channel.GetContact(request);
        }
        
        public UnitTestProject1.ServiceReference1.Contact GetContact(int id) {
            UnitTestProject1.ServiceReference1.GetContactRequest inValue = new UnitTestProject1.ServiceReference1.GetContactRequest();
            inValue.Body = new UnitTestProject1.ServiceReference1.GetContactRequestBody();
            inValue.Body.id = id;
            UnitTestProject1.ServiceReference1.GetContactResponse retVal = ((UnitTestProject1.ServiceReference1.WebService1Soap)(this)).GetContact(inValue);
            return retVal.Body.GetContactResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.GetContactResponse> UnitTestProject1.ServiceReference1.WebService1Soap.GetContactAsync(UnitTestProject1.ServiceReference1.GetContactRequest request) {
            return base.Channel.GetContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.GetContactResponse> GetContactAsync(int id) {
            UnitTestProject1.ServiceReference1.GetContactRequest inValue = new UnitTestProject1.ServiceReference1.GetContactRequest();
            inValue.Body = new UnitTestProject1.ServiceReference1.GetContactRequestBody();
            inValue.Body.id = id;
            return ((UnitTestProject1.ServiceReference1.WebService1Soap)(this)).GetContactAsync(inValue);
        }
    }
}
